### ISSUE TITLE
Is it possible to test it with vue-test-utils and trigger() helper?

### ISSUE THREAD

**Issue by vizcay** [shentao/vue-global-events#39]
I'm using, GlobalEvents inside a component. While testing that component with vue-test-utils and jest I'm trying to verify keyboard events related features. But I cannot use `trigger` on it:

```
  TypeError: Cannot read property 'length' of undefined

      54 |    wrapper.vm.show()
      55 |    expect(wrapper.find(GlobalEvents).exists).toBeTruthy()
    > 56 |    wrapper.find(GlobalEvents).trigger('keydown.down')
         |                               ^

      at VueWrapper.attributes (node_modules/@vue/test-utils/dist/vue-test-utils.js:3247:34)
      at VueWrapper.trigger (node_modules/@vue/test-utils/dist/vue-test-utils.js:3754:12)
      at Object.trigger (spec/javascript/ventas_pos/modals/modal_caja_spec.js:56:31)
```

Of course I'm not using `shallowMount`.

There is some way to accomplish this? Thanks

**Comment by posva** [comment]
A bit late but you need to trigger the events globally, on the window or document. This depends on the testing environment but usually, with jsdom you do:

```js
 const wrapper = mount(App, {
      attachTo: document.body,
    });
    document.dispatchEvent(
      new KeyboardEvent("keypress", { key: "a", bubbles: true })
    );
```
